name: CI-test

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  my-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la

      - name: Check current directiory

        run: |
          cd ~
          cp /home/runner/work/github-actions-test/github-actions-test/apache_script.sh /home/runner/apache_script.sh
          cp /home/runner/work/github-actions-test/github-actions-test/nginx_script.sh /home/runner/nginx_script.sh
          sudo chmod 777 apache_script.sh
          sudo chmod 777 nginx_script.sh
          ./apache_script.sh
          ./nginx_script.sh
          ls -ls
